// <auto-generated />
using DemoApp.SharedKernel.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DemoApp.SharedKernel.Migrations
{
    [DbContext(typeof(DemoAppDbContext))]
    [Migration("20210128122945_AddedDeviceAndUser")]
    partial class AddedDeviceAndUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("DemoApp.SharedKernel.Domain.Device.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manufacturer = "Manufacturer1",
                            Name = "Device1",
                            UserId = 10
                        },
                        new
                        {
                            Id = 2,
                            Manufacturer = "Manufacturer2",
                            Name = "Device2",
                            UserId = 10
                        },
                        new
                        {
                            Id = 3,
                            Manufacturer = "Manufacturer3",
                            Name = "Device3",
                            UserId = 10
                        });
                });

            modelBuilder.Entity("DemoApp.SharedKernel.Domain.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            FirstName = "Faruk",
                            LastName = "Ohran"
                        });
                });

            modelBuilder.Entity("DemoApp.SharedKernel.Domain.Device.Device", b =>
                {
                    b.HasOne("DemoApp.SharedKernel.Domain.User.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DemoApp.SharedKernel.Domain.User.User", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
